apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xdatabaseserver.example.io
spec:
  compositeTypeRef:
    apiVersion: example.io/v1alpha1
    kind: XDatabaseServer
  resources:
  - name: server-release
    base:
      apiVersion: helm.crossplane.io/v1beta1
      kind: Release
      metadata:
        annotations:
          crossplane.io/external-name: mariadb
      spec:
        forProvider:
          chart:
            name: mariadb
            repository: https://charts.bitnami.com/bitnami
            version: 13.1.3
          namespace: database-system
          values:
            auth:
              rootPassword: randomize-me
    patches:
      - fromFieldPath: spec.version
        toFieldPath: spec.forProvider.chart.version
  - name: database-connection-secret
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: v1
            kind: Secret
            metadata:
              name: database-connection
              namespace: database-system
            stringData:
              username: root
              password: randomize-me
              endpoint: mariadb.database-system.svc.cluster.local
              port: "3306"
  - name: providerconfig-sql
    base:
      apiVersion: mysql.sql.crossplane.io/v1alpha1
      kind: ProviderConfig
      spec:
        credentials:
          source: MySQLConnectionSecret
          connectionSecretRef:
            namespace: database-system
            name: database-connection
    patches:
      - fromFieldPath: metadata.labels[crossplane.io/claim-name]
        toFieldPath: metadata.name
    readinessChecks:
      - type: None