apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabaseservers.example.io
spec:
  group: example.io
  names:
    kind: XDatabaseServer
    plural: xdatabaseservers
  claimNames:
    kind: DatabaseServer
    plural: databaseservers
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
     openAPIV3Schema:
       type: object
       properties:
        spec:
          type: object
          properties:
            version:
              type: string
          required:
          - version